/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin26;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author Adri
 */
public class VentanaJuego extends javax.swing.JFrame {

    ArrayList<String> jugada = new ArrayList<>();
    ArrayList<String> resultado = new ArrayList<>();
    ArrayList<String> ganadora = new ArrayList<>();
    private int contador = 0;

    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        jC71 = new javax.swing.JCheckBox();
        jC61 = new javax.swing.JCheckBox();
        jC11 = new javax.swing.JCheckBox();
        jC21 = new javax.swing.JCheckBox();
        jC31 = new javax.swing.JCheckBox();
        jC41 = new javax.swing.JCheckBox();
        jC51 = new javax.swing.JCheckBox();
        jC12 = new javax.swing.JCheckBox();
        jC22 = new javax.swing.JCheckBox();
        jC32 = new javax.swing.JCheckBox();
        jC42 = new javax.swing.JCheckBox();
        jC52 = new javax.swing.JCheckBox();
        jC62 = new javax.swing.JCheckBox();
        jC72 = new javax.swing.JCheckBox();
        jC13 = new javax.swing.JCheckBox();
        jC23 = new javax.swing.JCheckBox();
        jC33 = new javax.swing.JCheckBox();
        jC43 = new javax.swing.JCheckBox();
        jC53 = new javax.swing.JCheckBox();
        jC63 = new javax.swing.JCheckBox();
        jC73 = new javax.swing.JCheckBox();
        jC14 = new javax.swing.JCheckBox();
        jC24 = new javax.swing.JCheckBox();
        jC34 = new javax.swing.JCheckBox();
        jC44 = new javax.swing.JCheckBox();
        jC54 = new javax.swing.JCheckBox();
        jC64 = new javax.swing.JCheckBox();
        jC74 = new javax.swing.JCheckBox();
        jC15 = new javax.swing.JCheckBox();
        jC25 = new javax.swing.JCheckBox();
        jC35 = new javax.swing.JCheckBox();
        jC45 = new javax.swing.JCheckBox();
        jC55 = new javax.swing.JCheckBox();
        jC65 = new javax.swing.JCheckBox();
        jC75 = new javax.swing.JCheckBox();
        jC16 = new javax.swing.JCheckBox();
        jC26 = new javax.swing.JCheckBox();
        jC36 = new javax.swing.JCheckBox();
        jC46 = new javax.swing.JCheckBox();
        jC56 = new javax.swing.JCheckBox();
        jC66 = new javax.swing.JCheckBox();
        jC76 = new javax.swing.JCheckBox();
        jC17 = new javax.swing.JCheckBox();
        jC27 = new javax.swing.JCheckBox();
        jC37 = new javax.swing.JCheckBox();
        jC47 = new javax.swing.JCheckBox();
        jC57 = new javax.swing.JCheckBox();
        jC67 = new javax.swing.JCheckBox();
        jC77 = new javax.swing.JCheckBox();
        labelUno = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jugadaUno = new javax.swing.JTextField();
        jugadaDos = new javax.swing.JTextField();
        jugadaTres = new javax.swing.JTextField();
        jugadaCuatro = new javax.swing.JTextField();
        jugadaCinco = new javax.swing.JTextField();
        jugadaSeis = new javax.swing.JTextField();
        resultadoUno = new javax.swing.JTextField();
        resultadoDos = new javax.swing.JTextField();
        resultadoTres = new javax.swing.JTextField();
        resultadoCuatro = new javax.swing.JTextField();
        resultadoCinco = new javax.swing.JTextField();
        resultadoSeis = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bonoloto");

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        panelJuego.setBackground(new java.awt.Color(13, 74, 115));

        jC71.setBackground(new java.awt.Color(13, 74, 115));
        jC71.setForeground(new java.awt.Color(255, 255, 255));
        jC71.setText("7");
        jC71.setBorder(null);

        jC61.setBackground(new java.awt.Color(13, 74, 115));
        jC61.setForeground(new java.awt.Color(255, 255, 255));
        jC61.setText("6");
        jC61.setBorder(null);

        jC11.setBackground(new java.awt.Color(13, 74, 115));
        jC11.setForeground(new java.awt.Color(255, 255, 255));
        jC11.setText("1");
        jC11.setBorder(null);

        jC21.setBackground(new java.awt.Color(13, 74, 115));
        jC21.setForeground(new java.awt.Color(255, 255, 255));
        jC21.setText("2");
        jC21.setBorder(null);

        jC31.setBackground(new java.awt.Color(13, 74, 115));
        jC31.setForeground(new java.awt.Color(255, 255, 255));
        jC31.setText("3");
        jC31.setBorder(null);

        jC41.setBackground(new java.awt.Color(13, 74, 115));
        jC41.setForeground(new java.awt.Color(255, 255, 255));
        jC41.setText("4");
        jC41.setBorder(null);

        jC51.setBackground(new java.awt.Color(13, 74, 115));
        jC51.setForeground(new java.awt.Color(255, 255, 255));
        jC51.setText("5");
        jC51.setBorder(null);

        jC12.setBackground(new java.awt.Color(13, 74, 115));
        jC12.setForeground(new java.awt.Color(255, 255, 255));
        jC12.setText("8");
        jC12.setBorder(null);

        jC22.setBackground(new java.awt.Color(13, 74, 115));
        jC22.setForeground(new java.awt.Color(255, 255, 255));
        jC22.setText("9");
        jC22.setBorder(null);

        jC32.setBackground(new java.awt.Color(13, 74, 115));
        jC32.setForeground(new java.awt.Color(255, 255, 255));
        jC32.setText("10");
        jC32.setBorder(null);

        jC42.setBackground(new java.awt.Color(13, 74, 115));
        jC42.setForeground(new java.awt.Color(255, 255, 255));
        jC42.setText("11");
        jC42.setBorder(null);

        jC52.setBackground(new java.awt.Color(13, 74, 115));
        jC52.setForeground(new java.awt.Color(255, 255, 255));
        jC52.setText("12");
        jC52.setBorder(null);

        jC62.setBackground(new java.awt.Color(13, 74, 115));
        jC62.setForeground(new java.awt.Color(255, 255, 255));
        jC62.setText("13");
        jC62.setBorder(null);

        jC72.setBackground(new java.awt.Color(13, 74, 115));
        jC72.setForeground(new java.awt.Color(255, 255, 255));
        jC72.setText("14");
        jC72.setBorder(null);

        jC13.setBackground(new java.awt.Color(13, 74, 115));
        jC13.setForeground(new java.awt.Color(255, 255, 255));
        jC13.setText("15");
        jC13.setBorder(null);

        jC23.setBackground(new java.awt.Color(13, 74, 115));
        jC23.setForeground(new java.awt.Color(255, 255, 255));
        jC23.setText("16");
        jC23.setBorder(null);

        jC33.setBackground(new java.awt.Color(13, 74, 115));
        jC33.setForeground(new java.awt.Color(255, 255, 255));
        jC33.setText("17");
        jC33.setBorder(null);

        jC43.setBackground(new java.awt.Color(13, 74, 115));
        jC43.setForeground(new java.awt.Color(255, 255, 255));
        jC43.setText("18");
        jC43.setBorder(null);

        jC53.setBackground(new java.awt.Color(13, 74, 115));
        jC53.setForeground(new java.awt.Color(255, 255, 255));
        jC53.setText("19");
        jC53.setBorder(null);

        jC63.setBackground(new java.awt.Color(13, 74, 115));
        jC63.setForeground(new java.awt.Color(255, 255, 255));
        jC63.setText("20");
        jC63.setBorder(null);

        jC73.setBackground(new java.awt.Color(13, 74, 115));
        jC73.setForeground(new java.awt.Color(255, 255, 255));
        jC73.setText("21");
        jC73.setBorder(null);

        jC14.setBackground(new java.awt.Color(13, 74, 115));
        jC14.setForeground(new java.awt.Color(255, 255, 255));
        jC14.setText("22");
        jC14.setBorder(null);

        jC24.setBackground(new java.awt.Color(13, 74, 115));
        jC24.setForeground(new java.awt.Color(255, 255, 255));
        jC24.setText("23");
        jC24.setBorder(null);

        jC34.setBackground(new java.awt.Color(13, 74, 115));
        jC34.setForeground(new java.awt.Color(255, 255, 255));
        jC34.setText("24");
        jC34.setBorder(null);

        jC44.setBackground(new java.awt.Color(13, 74, 115));
        jC44.setForeground(new java.awt.Color(255, 255, 255));
        jC44.setText("25");
        jC44.setBorder(null);

        jC54.setBackground(new java.awt.Color(13, 74, 115));
        jC54.setForeground(new java.awt.Color(255, 255, 255));
        jC54.setText("26");
        jC54.setBorder(null);

        jC64.setBackground(new java.awt.Color(13, 74, 115));
        jC64.setForeground(new java.awt.Color(255, 255, 255));
        jC64.setText("27");
        jC64.setBorder(null);

        jC74.setBackground(new java.awt.Color(13, 74, 115));
        jC74.setForeground(new java.awt.Color(255, 255, 255));
        jC74.setText("28");
        jC74.setBorder(null);

        jC15.setBackground(new java.awt.Color(13, 74, 115));
        jC15.setForeground(new java.awt.Color(255, 255, 255));
        jC15.setText("29");
        jC15.setBorder(null);

        jC25.setBackground(new java.awt.Color(13, 74, 115));
        jC25.setForeground(new java.awt.Color(255, 255, 255));
        jC25.setText("30");
        jC25.setBorder(null);

        jC35.setBackground(new java.awt.Color(13, 74, 115));
        jC35.setForeground(new java.awt.Color(255, 255, 255));
        jC35.setText("31");
        jC35.setBorder(null);

        jC45.setBackground(new java.awt.Color(13, 74, 115));
        jC45.setForeground(new java.awt.Color(255, 255, 255));
        jC45.setText("32");
        jC45.setBorder(null);

        jC55.setBackground(new java.awt.Color(13, 74, 115));
        jC55.setForeground(new java.awt.Color(255, 255, 255));
        jC55.setText("33");
        jC55.setBorder(null);

        jC65.setBackground(new java.awt.Color(13, 74, 115));
        jC65.setForeground(new java.awt.Color(255, 255, 255));
        jC65.setText("34");
        jC65.setBorder(null);

        jC75.setBackground(new java.awt.Color(13, 74, 115));
        jC75.setForeground(new java.awt.Color(255, 255, 255));
        jC75.setText("35");
        jC75.setBorder(null);

        jC16.setBackground(new java.awt.Color(13, 74, 115));
        jC16.setForeground(new java.awt.Color(255, 255, 255));
        jC16.setText("36");
        jC16.setBorder(null);

        jC26.setBackground(new java.awt.Color(13, 74, 115));
        jC26.setForeground(new java.awt.Color(255, 255, 255));
        jC26.setText("37");
        jC26.setToolTipText("");
        jC26.setBorder(null);

        jC36.setBackground(new java.awt.Color(13, 74, 115));
        jC36.setForeground(new java.awt.Color(255, 255, 255));
        jC36.setText("38");
        jC36.setBorder(null);

        jC46.setBackground(new java.awt.Color(13, 74, 115));
        jC46.setForeground(new java.awt.Color(255, 255, 255));
        jC46.setText("39");
        jC46.setBorder(null);

        jC56.setBackground(new java.awt.Color(13, 74, 115));
        jC56.setForeground(new java.awt.Color(255, 255, 255));
        jC56.setText("40");
        jC56.setBorder(null);

        jC66.setBackground(new java.awt.Color(13, 74, 115));
        jC66.setForeground(new java.awt.Color(255, 255, 255));
        jC66.setText("41");
        jC66.setBorder(null);

        jC76.setBackground(new java.awt.Color(13, 74, 115));
        jC76.setForeground(new java.awt.Color(255, 255, 255));
        jC76.setText("42");
        jC76.setBorder(null);

        jC17.setBackground(new java.awt.Color(13, 74, 115));
        jC17.setForeground(new java.awt.Color(255, 255, 255));
        jC17.setText("43");
        jC17.setBorder(null);

        jC27.setBackground(new java.awt.Color(13, 74, 115));
        jC27.setForeground(new java.awt.Color(255, 255, 255));
        jC27.setText("44");
        jC27.setBorder(null);

        jC37.setBackground(new java.awt.Color(13, 74, 115));
        jC37.setForeground(new java.awt.Color(255, 255, 255));
        jC37.setText("45");
        jC37.setBorder(null);

        jC47.setBackground(new java.awt.Color(13, 74, 115));
        jC47.setForeground(new java.awt.Color(255, 255, 255));
        jC47.setText("46");
        jC47.setBorder(null);

        jC57.setBackground(new java.awt.Color(13, 74, 115));
        jC57.setForeground(new java.awt.Color(255, 255, 255));
        jC57.setText("47");
        jC57.setBorder(null);

        jC67.setBackground(new java.awt.Color(13, 74, 115));
        jC67.setForeground(new java.awt.Color(255, 255, 255));
        jC67.setText("48");
        jC67.setBorder(null);

        jC77.setBackground(new java.awt.Color(13, 74, 115));
        jC77.setForeground(new java.awt.Color(255, 255, 255));
        jC77.setText("49");
        jC77.setBorder(null);

        labelUno.setForeground(new java.awt.Color(255, 255, 255));
        labelUno.setText("Escoge seis números:");

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUno)
                    .addGroup(panelJuegoLayout.createSequentialGroup()
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC71)
                            .addComponent(jC61)
                            .addComponent(jC51)
                            .addComponent(jC41)
                            .addComponent(jC31)
                            .addComponent(jC21)
                            .addComponent(jC11))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC72)
                            .addComponent(jC62)
                            .addComponent(jC52)
                            .addComponent(jC42)
                            .addComponent(jC32)
                            .addComponent(jC22)
                            .addComponent(jC12))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC73)
                            .addComponent(jC63)
                            .addComponent(jC53)
                            .addComponent(jC43)
                            .addComponent(jC33)
                            .addComponent(jC23)
                            .addComponent(jC13))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC74)
                            .addComponent(jC64)
                            .addComponent(jC54)
                            .addComponent(jC44)
                            .addComponent(jC34)
                            .addComponent(jC24)
                            .addComponent(jC14))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC75)
                            .addComponent(jC65)
                            .addComponent(jC55)
                            .addComponent(jC45)
                            .addComponent(jC35)
                            .addComponent(jC25)
                            .addComponent(jC15))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC76)
                            .addComponent(jC66)
                            .addComponent(jC56)
                            .addComponent(jC46)
                            .addComponent(jC36)
                            .addComponent(jC26)
                            .addComponent(jC16))
                        .addGap(18, 18, 18)
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC77)
                            .addComponent(jC67)
                            .addComponent(jC57)
                            .addComponent(jC47)
                            .addComponent(jC37)
                            .addComponent(jC27)
                            .addComponent(jC17))))
                .addGap(34, 34, 34))
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(labelUno)
                .addGap(18, 18, 18)
                .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelJuegoLayout.createSequentialGroup()
                        .addComponent(jC17)
                        .addGap(18, 18, 18)
                        .addComponent(jC27)
                        .addGap(18, 18, 18)
                        .addComponent(jC37)
                        .addGap(18, 18, 18)
                        .addComponent(jC47)
                        .addGap(18, 18, 18)
                        .addComponent(jC57)
                        .addGap(18, 18, 18)
                        .addComponent(jC67)
                        .addGap(18, 18, 18)
                        .addComponent(jC77))
                    .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelJuegoLayout.createSequentialGroup()
                            .addComponent(jC16)
                            .addGap(18, 18, 18)
                            .addComponent(jC26)
                            .addGap(18, 18, 18)
                            .addComponent(jC36)
                            .addGap(18, 18, 18)
                            .addComponent(jC46)
                            .addGap(18, 18, 18)
                            .addComponent(jC56)
                            .addGap(18, 18, 18)
                            .addComponent(jC66)
                            .addGap(18, 18, 18)
                            .addComponent(jC76))
                        .addGroup(panelJuegoLayout.createSequentialGroup()
                            .addComponent(jC15)
                            .addGap(18, 18, 18)
                            .addComponent(jC25)
                            .addGap(18, 18, 18)
                            .addComponent(jC35)
                            .addGap(18, 18, 18)
                            .addComponent(jC45)
                            .addGap(18, 18, 18)
                            .addComponent(jC55)
                            .addGap(18, 18, 18)
                            .addComponent(jC65)
                            .addGap(18, 18, 18)
                            .addComponent(jC75))
                        .addGroup(panelJuegoLayout.createSequentialGroup()
                            .addComponent(jC14)
                            .addGap(18, 18, 18)
                            .addComponent(jC24)
                            .addGap(18, 18, 18)
                            .addComponent(jC34)
                            .addGap(18, 18, 18)
                            .addComponent(jC44)
                            .addGap(18, 18, 18)
                            .addComponent(jC54)
                            .addGap(18, 18, 18)
                            .addComponent(jC64)
                            .addGap(18, 18, 18)
                            .addComponent(jC74))
                        .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelJuegoLayout.createSequentialGroup()
                                .addComponent(jC13)
                                .addGap(18, 18, 18)
                                .addComponent(jC23)
                                .addGap(18, 18, 18)
                                .addComponent(jC33)
                                .addGap(18, 18, 18)
                                .addComponent(jC43)
                                .addGap(18, 18, 18)
                                .addComponent(jC53)
                                .addGap(18, 18, 18)
                                .addComponent(jC63)
                                .addGap(18, 18, 18)
                                .addComponent(jC73))
                            .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelJuegoLayout.createSequentialGroup()
                                    .addComponent(jC12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC22)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC32)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC42)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC52)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC62)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC72))
                                .addGroup(panelJuegoLayout.createSequentialGroup()
                                    .addComponent(jC11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC21)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC31)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC41)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC51)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC61)
                                    .addGap(18, 18, 18)
                                    .addComponent(jC71))))))
                .addGap(30, 30, 30))
        );

        panelBotones.setBackground(new java.awt.Color(13, 74, 115));

        botonJugar.setBackground(new java.awt.Color(13, 74, 115));
        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(13, 74, 115));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonJugar)
                    .addComponent(botonSalir)))
        );

        jugadaUno.setBackground(new java.awt.Color(13, 74, 115));
        jugadaUno.setForeground(new java.awt.Color(255, 255, 255));

        jugadaDos.setBackground(new java.awt.Color(13, 74, 115));
        jugadaDos.setForeground(new java.awt.Color(255, 255, 255));

        jugadaTres.setBackground(new java.awt.Color(13, 74, 115));
        jugadaTres.setForeground(new java.awt.Color(255, 255, 255));

        jugadaCuatro.setBackground(new java.awt.Color(13, 74, 115));
        jugadaCuatro.setForeground(new java.awt.Color(255, 255, 255));

        jugadaCinco.setBackground(new java.awt.Color(13, 74, 115));
        jugadaCinco.setForeground(new java.awt.Color(255, 255, 255));

        jugadaSeis.setBackground(new java.awt.Color(13, 74, 115));
        jugadaSeis.setForeground(new java.awt.Color(255, 255, 255));

        resultadoUno.setBackground(new java.awt.Color(13, 74, 115));
        resultadoUno.setForeground(new java.awt.Color(255, 255, 255));

        resultadoDos.setBackground(new java.awt.Color(13, 74, 115));
        resultadoDos.setForeground(new java.awt.Color(255, 255, 255));

        resultadoTres.setBackground(new java.awt.Color(13, 74, 115));
        resultadoTres.setForeground(new java.awt.Color(255, 255, 255));

        resultadoCuatro.setBackground(new java.awt.Color(13, 74, 115));
        resultadoCuatro.setForeground(new java.awt.Color(255, 255, 255));

        resultadoCinco.setBackground(new java.awt.Color(13, 74, 115));
        resultadoCinco.setForeground(new java.awt.Color(255, 255, 255));

        resultadoSeis.setBackground(new java.awt.Color(13, 74, 115));
        resultadoSeis.setForeground(new java.awt.Color(255, 255, 255));

        label2.setForeground(new java.awt.Color(13, 74, 115));
        label2.setText("Tu jugada:");

        label3.setForeground(new java.awt.Color(13, 74, 115));
        label3.setText("Jugada ganadora:");

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3)
                    .addComponent(label2)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelFondoLayout.createSequentialGroup()
                            .addComponent(resultadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resultadoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resultadoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resultadoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resultadoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resultadoSeis))
                        .addGroup(panelFondoLayout.createSequentialGroup()
                            .addComponent(jugadaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jugadaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jugadaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jugadaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jugadaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jugadaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFondoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jugadaCinco, jugadaCuatro, jugadaDos, jugadaSeis, jugadaTres, jugadaUno});

        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jugadaCinco, jugadaCuatro, jugadaDos, jugadaSeis, jugadaTres, jugadaUno});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        checkBox();

        if (contador < 6) {
            JOptionPane.showMessageDialog(null, "Debes elegir seis números");
        } else if (contador == 6) {
            panelJuego.setEnabled(false);
        }
        Collections.sort(jugada, new Comparator<String>() {
            public int compare(String s1, String s2) {
                return Integer.valueOf(s1).compareTo(Integer.valueOf(s2));
            }
        });
        jugadaUno.setText((String) jugada.get(0));
        jugadaDos.setText((String) jugada.get(1));
        jugadaTres.setText((String) jugada.get(2));
        jugadaCuatro.setText((String) jugada.get(3));
        jugadaCinco.setText((String) jugada.get(4));
        jugadaSeis.setText((String) jugada.get(5));

        generarAleatorios();
        jugadaGanadora();
        Collections.sort(ganadora, new Comparator<String>() {
            public int compare(String s1, String s2) {
                return Integer.valueOf(s1).compareTo(Integer.valueOf(s2));
            }
        });

        resultadoUno.setText((String) ganadora.get(0));
        resultadoDos.setText((String) ganadora.get(1));
        resultadoTres.setText((String) ganadora.get(2));
        resultadoCuatro.setText((String) ganadora.get(3));
        resultadoCinco.setText((String) ganadora.get(4));
        resultadoSeis.setText((String) ganadora.get(5));

        /* Valor de un vector random para cada casilla resultado */

    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });

    }

    public void jugadaGanadora() {

        for (int i = 0; i < 6; i++) {
            Collections.shuffle(resultado);
            ganadora.add((String) resultado.get(0));
            resultado.remove(0);
        }

    }

    public void comprobarCampos(javax.swing.JCheckBox boton) {
        
        if (boton.isSelected()) {
            contador++;
            jugada.add(boton.getText());
        }

    }

    public void generarAleatorios() {

        for (int i = 1; i < 50; i++) {
            resultado.add(String.valueOf(i));
        }

    }

    public void checkBox() {
        comprobarCampos(jC11);
        comprobarCampos(jC12);
        comprobarCampos(jC13);
        comprobarCampos(jC14);
        comprobarCampos(jC15);
        comprobarCampos(jC16);
        comprobarCampos(jC17);
        comprobarCampos(jC21);
        comprobarCampos(jC22);
        comprobarCampos(jC23);
        comprobarCampos(jC24);
        comprobarCampos(jC25);
        comprobarCampos(jC26);
        comprobarCampos(jC27);
        comprobarCampos(jC31);
        comprobarCampos(jC32);
        comprobarCampos(jC33);
        comprobarCampos(jC34);
        comprobarCampos(jC35);
        comprobarCampos(jC36);
        comprobarCampos(jC37);
        comprobarCampos(jC41);
        comprobarCampos(jC42);
        comprobarCampos(jC43);
        comprobarCampos(jC44);
        comprobarCampos(jC45);
        comprobarCampos(jC46);
        comprobarCampos(jC47);
        comprobarCampos(jC51);
        comprobarCampos(jC52);
        comprobarCampos(jC53);
        comprobarCampos(jC54);
        comprobarCampos(jC55);
        comprobarCampos(jC56);
        comprobarCampos(jC57);
        comprobarCampos(jC61);
        comprobarCampos(jC62);
        comprobarCampos(jC63);
        comprobarCampos(jC64);
        comprobarCampos(jC65);
        comprobarCampos(jC66);
        comprobarCampos(jC67);
        comprobarCampos(jC71);
        comprobarCampos(jC72);
        comprobarCampos(jC73);
        comprobarCampos(jC74);
        comprobarCampos(jC75);
        comprobarCampos(jC76);
        comprobarCampos(jC77);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JCheckBox jC11;
    private javax.swing.JCheckBox jC12;
    private javax.swing.JCheckBox jC13;
    private javax.swing.JCheckBox jC14;
    private javax.swing.JCheckBox jC15;
    private javax.swing.JCheckBox jC16;
    private javax.swing.JCheckBox jC17;
    private javax.swing.JCheckBox jC21;
    private javax.swing.JCheckBox jC22;
    private javax.swing.JCheckBox jC23;
    private javax.swing.JCheckBox jC24;
    private javax.swing.JCheckBox jC25;
    private javax.swing.JCheckBox jC26;
    private javax.swing.JCheckBox jC27;
    private javax.swing.JCheckBox jC31;
    private javax.swing.JCheckBox jC32;
    private javax.swing.JCheckBox jC33;
    private javax.swing.JCheckBox jC34;
    private javax.swing.JCheckBox jC35;
    private javax.swing.JCheckBox jC36;
    private javax.swing.JCheckBox jC37;
    private javax.swing.JCheckBox jC41;
    private javax.swing.JCheckBox jC42;
    private javax.swing.JCheckBox jC43;
    private javax.swing.JCheckBox jC44;
    private javax.swing.JCheckBox jC45;
    private javax.swing.JCheckBox jC46;
    private javax.swing.JCheckBox jC47;
    private javax.swing.JCheckBox jC51;
    private javax.swing.JCheckBox jC52;
    private javax.swing.JCheckBox jC53;
    private javax.swing.JCheckBox jC54;
    private javax.swing.JCheckBox jC55;
    private javax.swing.JCheckBox jC56;
    private javax.swing.JCheckBox jC57;
    private javax.swing.JCheckBox jC61;
    private javax.swing.JCheckBox jC62;
    private javax.swing.JCheckBox jC63;
    private javax.swing.JCheckBox jC64;
    private javax.swing.JCheckBox jC65;
    private javax.swing.JCheckBox jC66;
    private javax.swing.JCheckBox jC67;
    private javax.swing.JCheckBox jC71;
    private javax.swing.JCheckBox jC72;
    private javax.swing.JCheckBox jC73;
    private javax.swing.JCheckBox jC74;
    private javax.swing.JCheckBox jC75;
    private javax.swing.JCheckBox jC76;
    private javax.swing.JCheckBox jC77;
    private javax.swing.JTextField jugadaCinco;
    private javax.swing.JTextField jugadaCuatro;
    private javax.swing.JTextField jugadaDos;
    private javax.swing.JTextField jugadaSeis;
    private javax.swing.JTextField jugadaTres;
    private javax.swing.JTextField jugadaUno;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel labelUno;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JTextField resultadoCinco;
    private javax.swing.JTextField resultadoCuatro;
    private javax.swing.JTextField resultadoDos;
    private javax.swing.JTextField resultadoSeis;
    private javax.swing.JTextField resultadoTres;
    private javax.swing.JTextField resultadoUno;
    // End of variables declaration//GEN-END:variables
}
